// Make to Models mapping
export const makeToModels: Record<string, string[]> = {
    Toyota: [
        // Sedans and hatchbacks
        "Corolla",
        "Camry",
        "Corolla Altis",
        "Axio",
        "Premio",
        "Yaris",
        "Crown",
        "Century",
        // SUVs and crossovers
        "RAV4",
        "Highlander",
        "Land Cruiser",
        "Land Cruiser 70",
        "Land Cruiser 300",
        "Fortuner",
        "Land Cruiser Prado",
        "Corolla Cross",
        "C-HR",
        "Kluger",
        "Raize",
        "Urban Cruiser",
        "Harrier",
        // Trucks and commercial vehicles
        "Hilux",
        "Hiace",
        "Dyna",
        "Coaster",
        "Lite Ace",
        // Minivans and MPVs
        "Alphard",
        "Prius Alpha",
        "Noah",
        "Voxy",
        "Avanza",
        "Veloz",
        "Vellfire",
        // Sports cars
        "GR86",
        "GR Yaris",
        // Electric and hybrid models
        "bZ4X",
        "Prius",
        "Yaris Cross",
        "RAV4 Hybrid",
        "Corolla Altis Hybrid",
        "Camry Hybrid",
        // Additional models (for backward compatibility)
        "4Runner",
        "Sienna",
        "Tacoma",
        "Tundra",
        "Avalon",
        "Venza",
        "Sequoia",
        "Lexus",
    ],
    Honda: [
        "Civic",
        "Accord",
        "CR-V",
        "Pilot",
        "Odyssey",
        "Ridgeline",
        "HR-V",
        "Passport",
        "Insight",
        "Fit",
        "Clarity",
    ],
    Nissan: [
        // Sedans
        "Altima",
        "Sentra",
        "Versa",
        "Almera",
        "Maxima",
        // Crossovers and SUVs
        "ARIYA",
        "Armada",
        "Kicks",
        "Magnite",
        "Murano",
        "Pathfinder",
        "Patrol",
        "Qashqai",
        "Rogue",
        "X-Trail",
        "Juke",
        // Trucks and Vans
        "Frontier",
        "Navara",
        "NV200",
        "Titan",
        // Sports Cars and EVs
        "Z",
        "370Z",
        "GT-R",
        "LEAF",
        "Leaf",
        // Other Models
        "Serena",
        "Note",
    ],
    Mazda: [
        "Mazda3",
        "Mazda6",
        "CX-3",
        "CX-5",
        "CX-9",
        "MX-5 Miata",
        "CX-30",
    ],
    Subaru: [
        "Outback",
        "Forester",
        "Crosstrek",
        "Legacy",
        "Impreza",
        "Ascent",
        "WRX",
        "BRZ",
    ],
    Mitsubishi: [
        "Outlander",
        "Eclipse Cross",
        "Mirage",
        "Lancer",
        "Montero",
    ],
    Suzuki: [
        "Swift",
        "Vitara",
        "SX4",
        "Jimny",
    ],
    Daihatsu: [],
    Isuzu: [],
    Lexus: [
        "ES",
        "IS",
        "LS",
        "GS",
        "RX",
        "NX",
        "GX",
        "LX",
        "UX",
        "LC",
        "RC",
    ],
    Acura: [
        "TLX",
        "ILX",
        "RLX",
        "RDX",
        "MDX",
        "NSX",
    ],
    BMW: [
        "3 Series",
        "5 Series",
        "7 Series",
        "X1",
        "X3",
        "X5",
        "X7",
        "Z4",
        "i3",
        "i8",
    ],
    "Mercedes-Benz": [
        "C-Class",
        "E-Class",
        "S-Class",
        "A-Class",
        "GLA",
        "GLC",
        "GLE",
        "GLS",
        "CLA",
        "G-Class",
    ],
    Audi: [
        "A3",
        "A4",
        "A6",
        "A8",
        "Q3",
        "Q5",
        "Q7",
        "Q8",
        "TT",
        "R8",
    ],
    Volkswagen: [
        "Jetta",
        "Passat",
        "Tiguan",
        "Atlas",
        "Golf",
        "Beetle",
        "Arteon",
    ],
    Porsche: [
        "911",
        "Cayenne",
        "Macan",
        "Panamera",
        "Boxster",
        "Cayman",
    ],
    Volvo: [
        "XC60",
        "XC90",
        "S60",
        "S90",
        "V60",
        "V90",
    ],
    Ford: [
        "F-150",
        "Mustang",
        "Explorer",
        "Escape",
        "Edge",
        "Expedition",
        "Focus",
        "Fusion",
        "Bronco",
        "Ranger",
    ],
    Chevrolet: [
        "Silverado",
        "Equinox",
        "Tahoe",
        "Suburban",
        "Traverse",
        "Malibu",
        "Cruze",
        "Camaro",
        "Corvette",
        "Trax",
    ],
    Jeep: [
        "Wrangler",
        "Grand Cherokee",
        "Cherokee",
        "Compass",
        "Renegade",
    ],
    Dodge: [
        "Challenger",
        "Charger",
        "Durango",
        "Journey",
    ],
    Ram: [
        "1500",
        "2500",
        "3500",
    ],
    Chrysler: [],
    Cadillac: [
        "Escalade",
        "XTS",
        "CT6",
        "XT5",
        "XT4",
    ],
    Buick: [
        "Enclave",
        "Encore",
        "LaCrosse",
    ],
    Lincoln: [
        "Navigator",
        "Aviator",
        "MKZ",
    ],
    GMC: [
        "Sierra",
        "Yukon",
        "Acadia",
    ],
    Hyundai: [
        "Tucson",
        "Santa Fe",
        "Elantra",
        "Sonata",
        "Kona",
        "Palisade",
    ],
    Kia: [
        "Sorento",
        "Sportage",
        "Telluride",
        "Optima",
        "Forte",
    ],
    Genesis: [
        "G70",
        "G80",
        "G90",
        "GV70",
        "GV80",
    ],
    Tesla: [
        "Model 3",
        "Model S",
        "Model X",
        "Model Y",
    ],
    Jaguar: [],
    "Land Rover": [],
    Mini: [],
    Fiat: [],
    "Alfa Romeo": [],
    Maserati: [],
    Bentley: [],
    "Rolls-Royce": [],
    Ferrari: [],
    Lamborghini: [],
    McLaren: [],
    "Aston Martin": [],
    Infiniti: [
        "Q50",
        "Q60",
        "QX50",
        "QX60",
        "QX80",
    ],
};

// Common body types - sorted alphabetically
export const bodyTypes = [
    "Convertible",
    "Coupe",
    "Crossover",
    "Hatchback",
    "Luxury",
    "Minivan",
    "Pickup Truck",
    "Sedan",
    "Sports Car",
    "SUV",
    "Van",
    "Wagon",
];

/** Common exterior colors for dropdowns; merged with API filter options in forms */
export const carColors = [
    "Beige",
    "Black",
    "Blue",
    "Bronze",
    "Brown",
    "Burgundy",
    "Champagne",
    "Gold",
    "Gray",
    "Green",
    "Grey",
    "Maroon",
    "Metallic Silver",
    "Navy",
    "Orange",
    "Pearl White",
    "Pink",
    "Purple",
    "Red",
    "Silver",
    "Teal",
    "Turquoise",
    "White",
    "Yellow",
];

/** Merged with API `fuels` in car forms */
export const fuelTypes = [
    "CNG",
    "Diesel",
    "Electric",
    "Gasoline",
    "Hybrid",
    "LPG",
    "Petrol",
    "Plug-in Hybrid",
];

/** Merged with API `transmissions` in car forms */
export const transmissionTypes = [
    "Automatic",
    "CVT",
    "Manual",
    "Semi-Automatic",
];

/** Merged with API `drives` in car forms (drivetrain) */
export const drivetrainTypes = [
    "2WD",
    "4WD",
    "AWD",
    "FWD",
    "RWD",
];
